volumes:
  grafana-volume:
  prometheus-volume:

networks:
  monitoring-network:
    driver: bridge

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:${PROMETHEUS_IMAGE_VERSION}
    restart: always
    ports:
      - "9090:9090"
    environment:
      - PROMETHEUS_CONFIG_PATH=${PROMETHEUS_CONFIG_PATH}
    volumes:
      - ./prometheus-volume:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-network

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:${NODE_EXPORTER_IMAGE_VERSION}
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitoring-network

  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_IMAGE_VERSION}
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana-volume:/var/lib/grafana
      - ./grafana-volume/logs:/var/log/grafana
    networks:
      - monitoring-network